services:
  - type: worker
    name: tamim-tg-bot
    runtime: node
    buildCommand: npm install
    startCommand: node tamim-tg-bot/index.js
    envVars:
      - key: NODE_ENV
        value: production
